---
title: Collaborative Housing
timezone: UTC
collections:
  oclt-opens-its-first-project:
    title: OCLT opens its first project!
    output: true
  pages:
    title: Pages
    output: true
    permalink: "/:path/index.html"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  who-we-are:
    title: Who we are
    output: true
description: 'Together we can build homes that work for the Thames Valley

'
url: https://collaborativehousing.org.uk/
gcaptcha: 6LdNn1AUAAAAAA-VLy7CCzufqQi7EhPyoWQwcHIM
include:
- ".htaccess"
- admin
exclude:
- package-lock.json
- package.json
- webpack.mix.js
- yarn.lock
- readme.md
- shipitfile.js
whitelist: []
plugins:
- jekyll-seo-tag
